### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by farhanahmed95** [pro100svitlo/FingerprintAuthDemo#1]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.pro100svitlo.fingerprintAuthHelper.FahListener.onFingerprintStatus(boolean, int, java.lang.CharSequence)' on a null object reference
       at com.pro100svitlo.fingerprintAuthHelper.FahManager.onAuthenticationSucceeded(FahManager.java:226)
       at android.hardware.fingerprint.FingerprintManager$MyHandler.sendAuthenticatedSucceeded(FingerprintManager.java:805)
       at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:757)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

**Comment by farhanahmed95** [comment]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.pro100svitlo.fingerprintAuthHelper.FahListener.onFingerprintStatus(boolean, int, java.lang.CharSequence)' on a null object reference
       at com.pro100svitlo.fingerprintAuthHelper.FahManager.onAuthenticationFailed(FahManager.java:207)
       at android.hardware.fingerprint.FingerprintManager$MyHandler.sendAuthenticatedFailed(FingerprintManager.java:811)
       at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:760)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

**Comment by pro100svitlo** [comment]
Hi!
Please give me little bit more information:
1. version of library that u use
2. device 
3. any flow to reproduce 
4. errorType

**Comment by farhanahmed95** [comment]
Version 1.1.5
Devices :Reported on LGLS992 but also happened on other phones.
Flow: totally random, i will try to get more details.

**Comment by pro100svitlo** [comment]
First of all, please try the last one version.
And also please add log of errorType.

**Comment by farhanahmed95** [comment]
version 1.1.7 seems to fix it but i am not 100% sure. Anyway thanks for your instant support.

**Comment by pro100svitlo** [comment]
Thanks for reporting!  
If you didn't catch this npe again, I will close this issue in a week.
Have a nice codding ;-)

**Comment by pro100svitlo** [comment]
@farhanahmed95 is everything okey?
can i close this issue?

**Comment by farhanahmed95** [comment]
Yup everything working fine.
Thanks for this awesome library.
